name: Microservices CI/CD

on:
  pull_request_target:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - customer
          - shopping

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect changed services
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            customer:
              - 'customer/**'
            shopping:
              - 'shopping/**'

      - name: Docker login
        if: steps.filter.outputs[matrix.service] == 'true'
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      - name: Build image
        if: steps.filter.outputs[matrix.service] == 'true'
        run: |
          cd ${{ matrix.service }}
          docker build -t sarrazogh/${{ matrix.service }}:pr-${{ github.event.pull_request.number }} .


      - name: Push image
        if: steps.filter.outputs[matrix.service] == 'true'
        run: |
          docker push sarrazogh/${{ matrix.service }}:pr-${{ github.event.pull_request.number }}
