name: Microservices CI/CD

on:
  pull_request:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ğŸ” Login Docker (UNE FOIS)
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
	- name: Debug docker auth
  		run: docker info


      # ğŸ” Detect changes
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            customer: 'customer/**'
            shopping: 'shopping/**'

      # ğŸ“¦ Customer
      - name: Build & push customer
        if: ${{ steps.filter.outputs.customer == 'true' }}
        run: |
          cd customer
          docker build -t my-dockerhub-user/customer:pr-${{ github.event.pull_request.number }} .
          docker push my-dockerhub-user/customer:pr-${{ github.event.pull_request.number }}

      # ğŸ“¦ Shopping
      - name: Build & push shopping
        if: ${{ steps.filter.outputs.shopping == 'true' }}
        run: |
          cd shopping
          docker build -t my-dockerhub-user/shopping:pr-${{ github.event.pull_request.number }} .
          docker push my-dockerhub-user/shopping:pr-${{ github.event.pull_request.number }}
