name: Microservices CI/CD

on:
  pull_request:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ğŸ” Docker login
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Debug docker auth
        run: docker info

      # ğŸ” Detect changes
      - name: Detect changed services
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            customer:
              - 'customer/**'
            shopping:
              - 'shopping/**'

      # ğŸ“¦ Customer
      - name: Build & push customer
        if: steps.filter.outputs.customer == 'true'
        run: |
          cd customer
          docker build -t sarrazogh/customer:pr-${{ github.event.pull_request.number }} .
          docker push sarrazogh/customer:pr-${{ github.event.pull_request.number }}

      # ğŸ“¦ Shopping
      - name: Build & push shopping
        if: steps.filter.outputs.shopping == 'true'
        run: |
          cd shopping
          docker build -t sarrazogh/shopping:pr-${{ github.event.pull_request.number }} .
          docker push sarrazogh/shopping:pr-${{ github.event.pull_request.number }}
